FROM python:3.12.4

WORKDIR /app

RUN apt -y update && apt -y upgrade

COPY . .

RUN pip install -r ./requirements.txt

# Expose the Flask app port
EXPOSE 8000

# Set the command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--log-level", "debug"]